name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup GIT
        run: |
      # Change to your git email and name
          git config user.email "ytzlax@gmail.com"
          git config user.name "ytzlax"

      - name: install,lint,test
        run: |
          npm ci --if-present
      # Before npm test yot need to config karma.conf.js to browsers: ['ChromeHeadless'] and singleRun: true
          npm run test --if-present
          npm run lint --if-present
      #
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master

        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: anothrNick
